# Generated by Django 4.2.6 on 2023-10-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentlyplayed',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='songlikedby',
            unique_together=set(),
        ),
    ]
