# Generated by Django 4.2.6 on 2023-10-05 19:05

import album.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=25)),
                ('album_image', models.ImageField(upload_to=album.models.file_directory_path)),
                ('album_bio', models.CharField(max_length=500)),
                ('album_info', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('album_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.singer')),
            ],
            options={
                'ordering': ['-date_created', 'album_name'],
                'unique_together': {('album_name', 'album_creator')},
            },
        ),
        migrations.CreateModel(
            name='AlbumLikedBy',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_subscribed', models.DateField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AlbumsLikedBy',
                'ordering': ['-date_subscribed'],
                'unique_together': {('album', 'user')},
            },
        ),
    ]
